name: Build and Upload to ACR

on:
    workflow_call:

jobs:
  build_upload:
    runs-on: ubuntu-latest
    name: Build and upload docker image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: newsapiregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        run: |
          docker build . -t newsapiregistry.azurecr.io/newsapi:latest 
          docker push newsapiregistry.azurecr.io/newsapi:latest