name: Deploy to Azure

on: 
  workflow_call:
  
permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main

    - name: 'Sign in via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'gnewsapi'
        images: 'newsapiregistry.azurecr.io/newsapi:latest'

    - name: Azure logout
      run: |
        az logout